### ISSUE TITLE
wierd behivour

### ISSUE THREAD

**Issue by zeltak** [alphapapa/org-bookmark-heading#3]
Hi

so i have this weird issue. when i try to use the org-bookmark-jump via a hydra it wont work after a restart, unless i physically open the buffer and then it works.
i tried evaluating this after an emacs restart (for a current bookmark named o.bgu)

```
(org-bookmark-jump "o.bgu") 
```
and i get this message

`cdr: Wrong type argument: listp, "o.bgu"Invalid face reference: quote`

is my syntax wrong?

best

Z

**Comment by alphapapa** [comment]
Hey Z,

`org-bookmark-jump` does not take a string but a bookmark "object," i.e. `C-h f org-bookmark-jump RET` says:

```
org-bookmark-jump is a Lisp function in `org-bookmark-heading.el'.

(org-bookmark-jump BOOKMARK)

Jump to BOOKMARK, where BOOKMARK is one whose
`front-context-string' is an org-id.
```

You can see a list of bookmarks in the variable `bookmark-alist`, which has a list of these bookmark "objects" (just lists, really).  So I guess what you want is something like:

```
(org-bookmark-jump (assoc "o.bgu" bookmark-alist))
```

Or you could make a function like:

```
(defun org-bookmark-jump-by-string (s)
  "Jump to bookmark named S."
  (org-bookmark-jump (assoc s bookmark-alist)))
```

And then you could call that with the string directly.

**Comment by zeltak** [comment]
thx!

Z

**Comment by zeltak** [comment]
hmm i was to quick to comment :)

this code give me an error (for a bookmark named 'o.bgu')

```
(defun zz/org-bookmark-jump-by-string (s)
  (interactive)
  "Jump to bookmark named S."
  (org-bookmark-jump (assoc o.bgu bookmark-alist)))
```

error:
`funcall-interactively: Wrong number of arguments: (lambda (s) (interactive) "Jump to bookmark named S." (org-bookmark-jump (assoc o\.bgu bookmark-alist))), 0`

thx

Z

**Comment by alphapapa** [comment]
Well, there are a few problems there.  :)  First, the docstring should come before `(interactive)`.  Then, you're passing `o.bgu` to `assoc` as a symbol instead of a string, so unless the value of `o.bgu` is the string `"o.bgu"`, the call to `assoc` won't work.

Try this:

``` el
(defun zz/org-bookmark-jump-by-string (s)
  "Jump to bookmark named S."
  (interactive)
  (org-bookmark-jump (assoc s bookmark-alist)))

(zz/org-bookmark-jump-by-string "o.bgu")
```

The hydra should look something like:

``` el
(defhydra hydra:org-bookmarks ()
  "Menu text..."
  ("o" (lambda ()
         (interactive)
         (zz/org-bookmark-jump-by-string "o.bgu"))))
```

You might want to make a macro for the lambdas if you're going to define a lot of them.

**Comment by zeltak** [comment]
hmm so i think this is better but the bug that still annoys me is that at launch if i issue

`(zz/org-bookmark-jump-by-string "h.nyc")`

(i have a bookmark called h.nyc)

i get an error:

```
Bookmark for org-id nil not found in open org files or agenda files, and file not found: nil
```

yet after the 2nd time i EVAL it it works!!..lol..i dont get it

thx!
Z

**Comment by alphapapa** [comment]
That's a configuration error of some kind.  You are probably trying to load the bookmark before loading packages like `org` or `org-bookmark-heading`, but running the function `org-bookmark-jump` calls the autoload which loads the rest of Org, so then it works the next time.  Or doing that causes the file containing the bookmark to get opened into buffers, which makes it available next time.  It sounds like that bookmark is missing the filename as well, so its file can't be loaded directly from the bookmark.

Here's what I suggest:
1.  Use `use-package` in your Emacs config to load Org-mode and this package.  This makes it easier to load things in the right order, defer them until needed, etc.  It makes a big difference in loading speed too.
2.  Recreate that bookmark, which should fix its record so that its filename is stored with it.

**Comment by zeltak** [comment]
hooray, it was indeed the order. so now i have org load before the bookmarks and all is well :)

thx for helping me debug this :)

best

Z
